
03-02-2018 22:41:23:654 - I: 	Bot is sending to many do nothing commands, if this continues it the bot will be killed off
03-02-2018 22:41:23:654 - D: 	Executing bot with following commands python.exe "bot.py" A "C:\Users\user\Desktop\Strategi Algoritma\tubes1stima\Game Engine -  Version 1.2.2\Game Engine\Replays\2018-02-03 22-39-57-489\Phase 2 - Round 86\A"
03-02-2018 22:41:23:655 - I: 	Executing process python.exe "bot.py" A "C:\Users\user\Desktop\Strategi Algoritma\tubes1stima\Game Engine -  Version 1.2.2\Game Engine\Replays\2018-02-03 22-39-57-489\Phase 2 - Round 86\A"
03-02-2018 22:41:23:733 - I: 	Bot has 4000ms to run before it will be forcefully killed
03-02-2018 22:41:23:866 - E: 	Output from bot: Traceback (most recent call last):
03-02-2018 22:41:23:866 - E: 	Output from bot:   File "bot.py", line 144, in <module>
03-02-2018 22:41:23:866 - E: 	Output from bot:     main(args.PlayerKey)
03-02-2018 22:41:23:866 - E: 	Output from bot:   File "bot.py", line 21, in main
03-02-2018 22:41:23:866 - E: 	Output from bot:     greedy(state['OpponentMap']['Cells'], state['PlayerMap']['Owner']['Energy'])
03-02-2018 22:41:23:866 - E: 	Output from bot:   File "bot.py", line 82, in greedy
03-02-2018 22:41:23:866 - E: 	Output from bot:     output_shot(*valid_cell)
03-02-2018 22:41:23:866 - E: 	Output from bot: UnboundLocalError: local variable 'valid_cell' referenced before assignment
03-02-2018 22:41:23:873 - E: 	Output from bot: 
03-02-2018 22:41:23:873 - I: 	Output from bot: 
03-02-2018 22:41:23:875 - I: 	Your bots total execution time was 00:00:00.2210224